version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'oasis2022'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "SPK"
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        API_PATH: "/"
        NETWORK_PATH: "/"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "false"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        SOCKET_ROOT: "/"
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""

    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      #192.168.31.244改为服务器局域网ip
      - 'db_host:192.168.31.244'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4001:4000

